### ISSUE TITLE
we face this issue after every 15-20 days and after reloading the service it starts working fine.

### ISSUE THREAD

**Issue by nishantcha1997** [vitabaks/postgresql_cluster#166]
we face this issue after every 15-20 days and after reloading the service it starts working fine.
I am sharing the error logs here:
```
 2022-04-18 13:26 +00:00: <--------------Error in Base Entity pgGetOneEntity --------------> { SequelizeConnectionAcquireTimeoutError: Operation timeout
at pool.acquire.catch.error (/var/******/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:289:52)
name: 'SequelizeConnectionAcquireTimeoutError',
parent:
Error: Operation timeout
at Timeout._timeout.setTimeout (/var******/node_modules/sequelize-pool/lib/Deferred.js:19:19)
at Shim.applySegment (/var/******/node_modules/newrelic/lib/shim/shim.js:1430:20)
 at Timeout.wrappedCallback (/var/*****/node_modules/newrelic/lib/shim/shim.js:1287:21)
at ontimeout (timers.js:436:11)
 at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
 at Timer.processTimers (timers.js:223:10),
original:
 Error: Operation timeout
at Timeout._timeout.setTimeout (/var/*****/node_modules/sequelize-pool/lib/Deferred.js:19:19)
at Shim.applySegment (/var/*****/node_modules/newrelic/lib/shim/shim.js:1430:20)
0  at Timeout.wrappedCallback (/var/*****/node_modules/newrelic/lib/shim/shim.js:1287:21)
 at ontimeout (timers.js:436:11)
   at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
 at Timer.processTimers (timers.js:223:10) }
```

_Originally posted by @nishantcha1997 in https://github.com/vitabaks/postgresql_cluster/discussions/165_

**Comment by vitabaks** [comment]
This log does not seem familiar to me, what is it from?

It is not clear to me yet how this is related to the cluster deployment playbook.

**Comment by vitabaks** [comment]
There may be many reasons

For example, network problems, or overflow of the pgbouncer pool (if it is used), saturation of connections, saturation of database server resources, etc.

This is not due to errors with a cluster deployment. Please contact your DBA to investigate the problem.

Or consider sponsor membership level https://www.patreon.com/vitabaks
