### ISSUE TITLE
Patroni 2.0.0 и подготовка локалей на машине

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#60]
На днях вышла новая версия патрони 2.0.0 и я неожиданно столкнулся с проблемой при равёртывании кластера.
У меня ошибка выглядела так (часть из ansible.log):
```
TASK [deploy-finish : Check postgresql cluster health] **************************************************************************
fatal: [10.10.2.16]: FAILED! => {"changed": false, "cmd": ["patronictl", "-c", "/etc/patroni/patroni.yml", "list"], "delta": "0:00:00.379505", "end": "2020-09-11 10:09:38.744379", "msg": "non-zero return code", "rc": 1, "start": "2020-09-11 10:09:38.364874", 
"stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/patronictl\", line 11, in <module>\n
    sys.exit(ctl())\n  File \"/usr/local/lib/python3.6/site-packages/click/core.py\", line 829, in __call__\n
    return self.main(*args, **kwargs)\n
  File \"/usr/local/lib/python3.6/site-packages/click/core.py\", line 760, in main\n
    _verify_python3_env()\n
  File \"/usr/local/lib/python3.6/site-packages/click/_unicodefun.py\", line 130, in _verify_python3_env\n
    \" mitigation steps.{}\".format(extra)\nRuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.\n\n
This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: aa_DJ.utf8, aa_ER.utf8, aa_ET.utf8, ....
```
здесь мы видим сообщение от одной из библиотек питона что-то насчет кодировок...
```
Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps. 
```
и как оказалось само развертывание patroni  было сложным :) (часть из лога патрони):
```
patroni[62783]: /var/run/postgresql:5432 - rejecting connections
patroni[62783]: 2020-09-11 10:07:16,494 ERROR: Can not fetch local timeline and lsn from replication connection
patroni[62783]: Traceback (most recent call last):
patroni[62783]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 735, in get_replica_timeline
patroni[62783]: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
patroni[62783]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
patroni[62783]: return next(self.gen)
patroni[62783]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 730, in get_replication_connection_cursor
patroni[62783]: with get_connection_cursor(**conn_kwargs) as cur:
patroni[62783]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
patroni[62783]: return next(self.gen)
patroni[62783]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
patroni[62783]: with psycopg2.connect(**kwargs) as conn:
patroni[62783]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
patroni[62783]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
patroni[62783]: psycopg2.OperationalError: could not connect to server: Connection refused
patroni[62783]: Is the server running on host "localhost" (::1) and accepting
patroni[62783]: TCP/IP connections on port 5432?
patroni[62783]: FATAL:  password authentication failed for user "replicator"
```
и эта ошибка повторялась несколько раз подряд, пока не смогла разрешиться...
```
patroni[62783]: 2020-09-11 10:07:19,770 ERROR: Can not fetch local timeline and lsn from replication connection
patroni[62783]: Traceback (most recent call last):
patroni[62783]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 735, in get_replica_timeline
patroni[62783]: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
patroni[62783]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
patroni[62783]: return next(self.gen)
patroni[62783]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 730, in get_replication_connection_cursor
patroni[62783]: with get_connection_cursor(**conn_kwargs) as cur:
patroni[62783]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
patroni[62783]: return next(self.gen)
patroni[62783]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
patroni[62783]: with psycopg2.connect(**kwargs) as conn:
patroni[62783]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
patroni[62783]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
patroni[62783]: psycopg2.OperationalError: could not connect to server: Connection refused
patroni[62783]: Is the server running on host "localhost" (::1) and accepting
patroni[62783]: TCP/IP connections on port 5432?
patroni[62783]: FATAL:  password authentication failed for user "replicator"
patroni[62783]: 2020-09-11 10:07:25,406 INFO: Lock owner: sfactspostgres1; I am sfactspostgres1
patroni[62783]: 2020-09-11 10:07:25,861 INFO: Lock owner: sfactspostgres1; I am sfactspostgres1
patroni[62783]: 2020-09-11 10:07:26,576 INFO: no action.  i am the leader with the lock
patroni[62783]: 2020-09-11 10:07:27,486 INFO: Lock owner: sfactspostgres1; I am sfactspostgres1
patroni[62783]: 2020-09-11 10:07:27,692 INFO: no action.  i am the leader with the lock
```
за это время БД успела уже переключиться на Timeline 4, когда при обычном режиме равёртывания я всегда получал на выходе Timeline 2
Поиск проблемы занял пару дней и ещё пару дней экспериментов.

Итого:
добавление в файл `/etc/environment` язык активной локали (для английского):
```
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
```
полностью решает эту проблему!

Патрони ставится без проблем и ошибок :)

Предлагаю в роль `locales` доработать и прописывать в этот файл строчки текущей локали.

**Comment by vitabaks** [comment]
> в файл /etc/environment язык активной локали (для английского):

Принято. Добавлю.

А вот это уже не связанно с локалью:
> patroni[62783]: psycopg2.OperationalError: could not connect to server: Connection refused
> patroni[62783]: Is the server running on host "localhost" (::1) and accepting
> patroni[62783]: TCP/IP connections on port 5432?
> patroni[62783]: FATAL:  password authentication failed for user "replicator"

Здесь у Вас проблема коннекта по IPv6 для replication. 
Эта ошибка, я так понимаю, была в момент инициализации кластера Patroni в режие postgresql_exists='true'.
Если так, то далее после старта Patroni, через пару секунд, будут обновлены пароли пользователей postgres и replication (таск "Prepare PostgreSQL | make sure the user are present, and password does not differ from the specified"), и ошибка перестанет сыпаться.

В теории, можно и от этих ошибок избавиться, если добавить trust для локальных адресов 127.0.0.1/32 и ::1/128
```
  host      replication              replicator               127.0.0.1/32             trust
  host      replication              replicator               ::1/128                  trust
```

**Comment by sgrinko** [comment]
Спасибо.

**Comment by vitabaks** [comment]
Готово (fc3c5f6d1e4c35d906cb2c856492f746522a53fe)

**Comment by sgrinko** [comment]
Спасибо!
