### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for patroni

### ISSUE THREAD

**Issue by umutoguz** [vitabaks/postgresql_cluster#654]
Hi Vitabaks,
We receive the following error when running Patroni on the RHEL9 operating system.
Can you help us?

```
May 07 15:30:24 patroni[152654]: Traceback (most recent call last):
May 07 15:30:24 patroni[152654]:   File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 563, in from_name
May 07 15:30:24 patroni[152654]:     return next(cls.discover(name=name))
May 07 15:30:24 patroni[152654]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 07 15:30:24 patroni[152654]: StopIteration
May 07 15:30:24 patroni[152654]: During handling of the above exception, another exception occurred:
May 07 15:30:24 patroni[152654]: Traceback (most recent call last):
May 07 15:30:24 patroni[152654]:   File "/usr/bin/patroni", line 33, in <module>
May 07 15:30:24 patroni[152654]:     sys.exit(load_entry_point('patroni==3.2.2', 'console_scripts', 'patroni')())
May 07 15:30:24 patroni[152654]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 07 15:30:24 patroni[152654]:   File "/usr/bin/patroni", line 22, in importlib_load_entry_point
May 07 15:30:24 patroni[152654]:     for entry_point in distribution(dist_name).entry_points
May 07 15:30:24 patroni[152654]:                        ^^^^^^^^^^^^^^^^^^^^^^^
May 07 15:30:24 patroni[152654]:   File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 981, in distribution
May 07 15:30:24 patroni[152654]:     return Distribution.from_name(distribution_name)
May 07 15:30:24 patroni[152654]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 07 15:30:24 patroni[152654]:   File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 565, in from_name
May 07 15:30:24 patroni[152654]:     raise PackageNotFoundError(name)
May 07 15:30:24 patroni[152654]: importlib.metadata.PackageNotFoundError: No package metadata was found for patroni
```

**Comment by vitabaks** [comment]
@umutoguz Did you install the cluster through automation or were there manual actions? Could you attach more patroni log?
