### ISSUE TITLE
PGPass replicator auth problem

### ISSUE THREAD

**Issue by byazrail** [vitabaks/postgresql_cluster#69]
pgpass is problem?

Oct 15 00:57:23 pgnode02 patroni: psycopg2.OperationalError: could not connect to server: Connection refused
Oct 15 00:57:23 pgnode02 patroni: Is the server running on host "localhost" (::1) and accepting
Oct 15 00:57:23 pgnode02 patroni: TCP/IP connections on port 5432?
Oct 15 00:57:23 pgnode02 patroni: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "replicator", SSL off
Oct 15 00:57:23 pgnode02 patroni: 2020-10-15 00:57:23,697 ERROR: Can not fetch local timeline and lsn from replication connection
Oct 15 00:57:23 pgnode02 patroni: Traceback (most recent call last):
Oct 15 00:57:23 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 685, in get_local_timeline_lsn_from_replication_connection
Oct 15 00:57:23 pgnode02 patroni: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
Oct 15 00:57:23 pgnode02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Oct 15 00:57:23 pgnode02 patroni: return next(self.gen)
Oct 15 00:57:23 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 679, in get_replication_connection_cursor
Oct 15 00:57:23 pgnode02 patroni: with get_connection_cursor(**conn_kwargs) as cur:
Oct 15 00:57:23 pgnode02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Oct 15 00:57:23 pgnode02 patroni: return next(self.gen)
Oct 15 00:57:23 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Oct 15 00:57:23 pgnode02 patroni: with psycopg2.connect(**kwargs) as conn:
Oct 15 00:57:23 pgnode02 patroni: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Oct 15 00:57:23 pgnode02 patroni: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Oct 15 00:57:23 pgnode02 patroni: psycopg2.OperationalError: could not connect to server: Connection refused
Oct 15 00:57:23 pgnode02 patroni: Is the server running on host "localhost" (::1) and accepting
Oct 15 00:57:23 pgnode02 patroni: TCP/IP connections on port 5432?
Oct 15 00:57:23 pgnode02 patroni: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "replicator", SSL off
Oct 15 00:57:23 pgnode02 patroni: 2020-10-15 00:57:23,940 ERROR: Can not fetch local timeline and lsn from replication connection
Oct 15 00:57:23 pgnode02 patroni: Traceback (most recent call last):
Oct 15 00:57:23 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 685, in get_local_timeline_lsn_from_replication_connection
Oct 15 00:57:23 pgnode02 patroni: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
Oct 15 00:57:23 pgnode02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Oct 15 00:57:23 pgnode02 patroni: return next(self.gen)
Oct 15 00:57:23 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 679, in get_replication_connection_cursor
Oct 15 00:57:23 pgnode02 patroni: with get_connection_cursor(**conn_kwargs) as cur:
Oct 15 00:57:23 pgnode02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Oct 15 00:57:23 pgnode02 patroni: return next(self.gen)
Oct 15 00:57:23 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Oct 15 00:57:23 pgnode02 patroni: with psycopg2.connect(**kwargs) as conn:
Oct 15 00:57:23 pgnode02 patroni: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Oct 15 00:57:23 pgnode02 patroni: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Oct 15 00:57:23 pgnode02 patroni: psycopg2.OperationalError: could not connect to server: Connection refused
Oct 15 00:57:23 pgnode02 patroni: Is the server running on host "localhost" (::1) and accepting
Oct 15 00:57:23 pgnode02 patroni: TCP/IP connections on port 5432?
Oct 15 00:57:23 pgnode02 patroni: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "replicator", SSL off
Oct 15 00:57:24 pgnode02 patroni: 2020-10-15 00:57:24,342 ERROR: Can not fetch local timeline and lsn from replication connection
Oct 15 00:57:24 pgnode02 patroni: Traceback (most recent call last):
Oct 15 00:57:24 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 685, in get_local_timeline_lsn_from_replication_connection
Oct 15 00:57:24 pgnode02 patroni: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
Oct 15 00:57:24 pgnode02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Oct 15 00:57:24 pgnode02 patroni: return next(self.gen)
Oct 15 00:57:24 pgnode02 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 679, in get_replication_connection_cursor
Oct 15 00:57:24 pgnode02 patroni: with get_connection_cursor(**conn_kwargs) as cur:

**Comment by byazrail** [comment]
Oct 15 01:22:10 pgnode02 patroni: pg_basebackup: error: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "replicator", SSL off
Oct 15 01:22:10 pgnode02 patroni: 2020-10-15 01:22:10,112 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Oct 15 01:22:10 pgnode02 patroni: 2020-10-15 01:22:10,113 ERROR: failed to bootstrap from leader 'pgnode01'

**Comment by byazrail** [comment]
replicator user md5 change trust problem fixed.

https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/templates/pg_hba.conf.j2
```
# replication privilege.
  host      replication              {{ patroni_replication_username }}               localhost                trust
  host      replication              {{ patroni_replication_username }}               127.0.0.1/32            trust
{% for host in groups['postgres_cluster'] %}
  host      replication              {{ patroni_replication_username }}               {{ hostvars[host]['inventory_hostname'] }}/32         trust
{% endfor %}
```

https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/templates/patroni.yml.j2
```
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication {{ patroni_replication_username }} 127.0.0.1/32 trust
```
